// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"music/app/model/internal"
)

// Article is the golang structure for table article.
type Article internal.Article

// Fill with you ideas below.
