// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"github.com/gogf/gf/util/gmeta"
	"music/app/model/internal"
)

// Song is the golang structure for table song.
type Song internal.Song

// Fill with you ideas below.

type SongApiListReq struct {
	Page  int `v:"required|min:1#页码不能为空|页面最小为1"`
	Limit int `v:"required|min:5|max:10#必须指定每页的数据量|每页数据最少不少于5条，最多不大于50|每页数据最少不少于5条，最多不大于50"`
}

type SongApiInfoReq struct {
	SongId uint `v:"required#歌曲id不能为空"`
}

type SongListItem struct {
	gmeta.Meta      `orm:"table:song"`
	Id              uint       `json:"id"`
	UserId          uint       `json:"userId"`
	CoverPictureUrl string     `json:"coverPictureUrl"`
	SongUrl         string     `json:"songUrl"`
	CnName          string     `json:"cnName"`
	EnName          string     `json:"enName"`
	CommentCount    uint       `json:"commentCount"`
	ThumbUpCount    uint       `json:"thumbUpCount"`
	ReadCount       uint       `json:"readCount"`
	User            *QueryUser `orm:"with:id=UserId"`
}
