// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"music/app/model/internal"
)

// Song is the golang structure for table song.
type Song internal.Song

// Fill with you ideas below.
