// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"music/app/model/internal"
)

// User is the golang structure for table user.
type User internal.User

// Fill with you ideas below.
