// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"music/app/model/internal"
)

// Video is the golang structure for table video.
type Video internal.Video

type VideoApiListReq struct {
	Page  int `v:"#页码不能为空"`
	Limit int `v:"#每页数据最少不少于5条，最多不大于50"`
	Type  string
}
