// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"music/app/model/internal"
)

// Video is the golang structure for table video.
type Video internal.Video

// Fill with you ideas below.
