// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// User is the golang structure for table user.
type User struct {
	Id              int    `orm:"id,primary"      json:"id"`              //
	CoverPictureUrl string `orm:"coverPictureUrl" json:"coverPictureUrl"` //
	Nickname        string `orm:"nickname"        json:"nickname"`        //
	Type            string `orm:"type"            json:"type"`            // 角色 NORMAL_USER DQ_SINGER DQ_OFFICIAL_ACCOUNT
	MusicCount      int    `orm:"musicCount"      json:"musicCount"`      //
	MusicPlayCount  int    `orm:"musicPlayCount"  json:"musicPlayCount"`  //
}
