// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// Video is the golang structure for table video.
type Video struct {
	Id              int    `orm:"id,primary"      json:"id"`              //
	UserId          int    `orm:"userId"          json:"userId"`          //
	CoverPictureUrl string `orm:"coverPictureUrl" json:"coverPictureUrl"` //
	VideoUrl        string `orm:"videoUrl"        json:"videoUrl"`        //
	Title           string `orm:"title"           json:"title"`           //
	Intro           string `orm:"intro"           json:"intro"`           //
	CommentCount    int    `orm:"commentCount"    json:"commentCount"`    //
	ThumbUpCount    int    `orm:"thumbUpCount"    json:"thumbUpCount"`    //
	ReadCount       int    `orm:"readCount"       json:"readCount"`       //
	ShareCount      int    `orm:"shareCount"      json:"shareCount"`      //
	ContentSeconds  int    `orm:"contentSeconds"  json:"contentSeconds"`  //
}
