// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"music/app/dao/internal"
)

// songDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type songDao struct {
	internal.SongDao
}

var (
	// Song is globally public accessible object for table song operations.
	Song = songDao{
		internal.Song,
	}
)

// Fill with you ideas below.
