// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ArticleDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ArticleDao struct {
	gmvc.M                 // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB         // DB is the raw underlying database management object.
	Table   string         // Table is the table name of the DAO.
	Columns articleColumns // Columns contains all the columns of Table that for convenient usage.
}

// ArticleColumns defines and stores column names for table article.
type articleColumns struct {
	Id           string //
	UserId       string //
	CoverUrlList string // 多个英文逗号分割 最多四张
	Title        string //
	CommentCount string //
	ThumbUpCount string //
	ReadCount    string //
}

var (
	// Article is globally public accessible object for table article operations.
	Article = ArticleDao{
		M:     g.DB("default").Model("article").Safe(),
		DB:    g.DB("default"),
		Table: "article",
		Columns: articleColumns{
			Id:           "id",
			UserId:       "userId",
			CoverUrlList: "coverUrlList",
			Title:        "title",
			CommentCount: "commentCount",
			ThumbUpCount: "thumbUpCount",
			ReadCount:    "readCount",
		},
	}
)
